language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "XpFDZKtWIrFYA8TpxM9kVbQjBvC7L2RSB1ZqxOL2Ba5ro0oo6fewec78brY09G9MJFeijA2MIMW1zUTHqu6oW/nCA4jIbk2g9UqLGwX1GqB0pLIPxkoU3XUao7umVDJW3OZ0S/uDOwqa8YaQiyMN1rCfC91JUpdDurAY/tog3c1VPU18bjO/H2LEiHFrecJZ05xmJbKQxbJlb9dc6AHabjfQm8sqbOyiYFM6J+6SFD4fIRd/dyAmQlLjdOJ35AfjWaGY7D9krVjVBrN6b2kxHkadalP9ii0Zutm74f4jJgoiHuOTQYK/HbFKftVBDuI5EmC49DqCMO0sO1wPuEJkbFJayJ/FGIbEQHf7kCaKp2lj8lSUs1IAEHAErZ8vI8fJdQTTYTVvFyNJMk3UbDxg96IjKjkDq7ZnpGUlEXECwWtV/FvwfCRewg5oWYu6znMSKZrFpMP8m4KtCbyWpZlW0/CN7fCJ83E2ApD8HQlG8N6J2d1snYsvwjNatXyn3XOnJfILXJXbwiJ6hEj4Md0idIUm75AaE9p1kMeyZyszEYCMzSks7FEYtJN3irCQDyccXLlAGlluS7+DITomTNRWlHXhebBNKDS62ovi+870O5Gj1OKQm8z4J0WWGYI9wox7W1EctJkymUmvupvXIQekbA5FxuKD718DBjps8dm+dgo="
    - # ^^ OSSRH_PASSWORD
    - secure: "KuU34GauKu6UT66uQPaQgS/mC75DlMnNADHW48bJXflFtPkRaB1NUHnUJ5AIFJfZLEY41yF17JFTcabmXaBZSXEm1+1q3jM+VKAF2F8u4KXlR1LUwJti8d6MzNNXHiJuaZCjivE9gwwDMKNM5zBSvvcXDIAvQCE/a/88JhfYzf5qccDF1nWtwFM4/1HcbE3OxmqDazPfD+tNjv53vDXOr7nZHTtKrMCdSl2ZbcQZFQNlqhNrhGbvpsu7TSdLVgmWRbPRE2Ug1QO3njVQbz6Sr+XpqIH+NRtFGbq67+rgYjdjn3p2c+M1uL2D2WaUP4zZuBRjGXtqucxXKDnNC5Gxb3P0lHSEaUnQvdW/RPbLzJ0P+3FYlWTjalGUR6Zn5TGzvJRywi6eokcgqQWioFE4q9a+8L20cGz9b4BpWiMw+O/nBB54FdbvKovd+Jsb9CXf21vzTlEXe4Myyi0JJTwRPbFSBQT4ZF15WffOm3Li0gZwzpS0srKqefKrdbBZNgfLNlViIr5OEYRECLx02BYBq+l/qc/ysM/nLMSRBodjQoMTbR8i9iAj2ubVE3nx62e0jSxyRn8fETkJJLbYG7SVxlqXhIRgpWeYeZ+NlXnwxzUsX2v8lCwlflb8j7m5zMxlI8qjNz3OdDDnyXehQXYspJoKCdLTLwEyWSArMebXpZ0="
    - # ^^ GPG_KEY_NAME
    - secure: "Pi45dLVzkcOKSyvOeCHCm/IyzfOwjX1s9vE7/YnDgZlADxXZs6DmRG4XELunbuuYC1KWtxMeeAtfASIRxL7vrsmqo3/NZ38Vqmu2FlsR9T/eOkbn3czVxofsLssZGoVPs4DNLfu9Fn8IZ7ZlXIPrHvECCSy0k8UJvsCe5XEWrWQIs/HJm/+9u3my7mYiEKeoJWMJW80KJ8ADaIp7wDe8xSIdWGzh4SXw4O223bpSG15PCaRNt0535VFdkQxfK7AN2gFiTV4nYuNLR8jdNcEQ8x/0iWeHlLAnNw8Oq+wBEHPR0nDGgUSxOdp4HryAcaprOmyJH7qFuvrk31epwg/cNbc6xBKw5RCh2Y1vLP+txoN0aulJBX4CSGLfzzvGf4LmWPTqztSJ6R7Ur30t4wtVI6z7UWhUsZEvTofiWUYUwmBCU2ZVei72dUs+zL0yt1wX6Hx0HaED0Cpdz0Xrk5nmuS7/5A8Eeafvs4zvxKueePFj5RbqQuwSI5JJNazZJRGnhAdGGkc6FR3DuW81XKalrG8L40GU4/NV3nA1dypcHHVAVC/l4anSnFbOuX88uU50oFrehBzAZZNOs1vpe1DvYG4LhVjRLnA99BhLjcLbzQk2heYQLiP3ohfZE2UVaYniA+R3KlP1BbxfYrNdVVsF3twM25gqRq3pFSF6vK/K8JI="
    - # ^^ GPG_PASSPHRASE
    - secure: "hDVO/+B/KBzkJ/VnDE7Gt5zjb7E5BCAQMZ//LqQ+g3pUU/LrQdzSUOg14ftx2TSrPJEagrBDl5krGC+gvDVV3+9WOeiTcvPrq1u4EdeO5TTbgd8FNdWuBpdf1VLNYB6QpZpl3jRWJZ318FcQzXyJyE4SBAp/JjKHLwTseLoEskIIqn3kU0aDg/7a6igZnFYk4v16kFdH1t6sOgt7qn6AZth6lq3yjr1EfqGPU1woRF/pozl6V6bwBMbPpABDJKH0SAisxLnIW2+Ivc+9rNgdiIuXysxOn5YR9ql+fzYRKHeUFT3XUoWYAyFatkKKSnw0fVANnv+wFirR9K8U/aLu97d0q76ftvDUbbU7u/TVtiJgSKstiiZ7vApRFqhWnyGC52T/QQ8lvuPJ7HWrmYN3vk0Y34z0RSEyrAc5Akwwbkv1RO/Qn4aH8D1PO0V2pi5pIqIRAK/4GM9IY4S/zjRrYO1XwP8jf3ZbvMdoHtlWaKhmre3lfQ4OIv7eiOev8MCzt2bTSBDcOGpjsvUowVOgP6IR5yiEwChGDr4SW2PF0y1dJ/QWgYyvVmESNnYCWhV6ZBWJq9qxN06IFAukR2W7LrGUbI3I+5IXhbn4fNP1TkiyEZgQw27pWmf7hTOtqwOqyn2bdTbUFCuqm0QrISYS/0IR9hLuvfVMB8DOXxcx2HE="
before_install:
  - openssl aes-256-cbc -K $encrypted_65add4e3a431_key -iv $encrypted_65add4e3a431_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --yes --batch --import codesigning.asc
jdk:
  - oraclejdk8
install: mvn clean install -P !ossrh -B -V -U
script:
- mvn deploy -P ossrh --settings mvnsettings.xml
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - 6.3/master
    - 6.3/develop                                                            
notifications:
  email:
    on_success: change
    on_failure: change