language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "H9UpZJa/OtRCOyTbonzm1UijNnlEtXivJ061v+J0JLX8uU37WxU+JcURptVt+hclDLuU6Uy2qensYXjzWPUIz33lIJG2X6bjDnbUQ6tsUBIQPouD6Rvqi52eWU7DHpgHlHwMx056GsEJcuBDNjh5vVPqgAonWF9UU06XuxojrJDXIPzMEEj9nLTXDzx50QJMMIfZtG+lXsJB96+I0+T8U4OgNm9JResak6LRkEsUoqGflMHsamlzlDw9mLoZo46s4JtETw1UzMFi587Tx8QcyO8r1QM0IfxrzsEavN+AEd1/BcbXaIpSUb3lV6vtqNeo7BR8vx3N2ZJ6IdfonSI6ll8VsVreWLu6dxWWJfsXP9tSSFGbVtdwHc3u1hk5IVEoLYwdqBNIFp8pZOSIgkElKrSAIXRtVHTGoVQbV5MR6tFhZHlx2eJCDvL8TkqsvoLcBwugrTLu2IEJULXgipKOr+W5MAHX6IzGoA4kvc0wLW0jUs9OGXJDxVNn5qDlh7f/SI6XKmpu7HYepo5qFzP4jE1Wy7KEnF32qrG0ZDN7ilJGsx2K6BwcYB6EZNVVj3T0b8QULY3N14A9LP5IHpiz38cuh/PBZzxnAriJs+kDUUiDKzKXbdh2e/1KxTkj9JoiQ3TkPPe4UqsCQ+dZkfYK0p9r1yPNaQgfexMoRzaGRx4="
    - # ^^ OSSRH_PASSWORD
    - secure: "ExyKtTC2g9N0jjGWjvluGxEDV07lS1p0O8f0zE11OI0nKo6kc9HhWUUdckJxQnUbg/18VwOn1sQb2lVFs64zTEomkI6zQV4yw8jq1bTkIfEuZwuMJ1JD7uAoHQ+KHibX9zswuGzOdYFYe+XrnGCUS+EHvIGmkgYlxW/RTEAs3M/CAAYLSPKpR0I9hhmnTrRNZQdOBb9KS8JixOZtctCyidYip/qbos8tdiA/WnZk1mg/sjo+CNY7VW4jUyzU2r4M5QQ4efuqdYWdVsW4ojkjsVGJ9W0hpBdoNgSofINmTCLWP1GlcZEs5TUK3ACDaWTzfQDaISFhwqmHDjSDdB5YbJmrQcXbYEk0toYsxTTzIlQW7BRsHSDuG7gQFgZF/RYGj4w6AIqMbJK1Z6UiotR5NptDuFZXUWPPQUoxaoI+mJS2gUYpuZzpWQxfXh0+TjnTpDDzOS/2NYu5riEFavKx9BBALmQwLbbV+fHwD11wzKuuOl2fZmNYBLdyZF58QrSnAczzjFB0Dis32avmtOgc9LBYaFIX1CockYgVFQDcj3v7FE3RPSm4m7LlJvYqRCan/IAk3RKN2WCFUCd3JDGbaarOP7xtx19fQhODm104NfgJkzyBo7hGSrOe/6Uowg8mqExPR3EV3l57LGeee4R8obwi0EBm6y1Wha7oZOkVvio="
    - # ^^ GPG_KEY_NAME
    - secure: "MaO9C1ZhWuHNE2//y5YKx+sylxdpl+76o1wwR8ifehHmC19VUDuFHIqjld1DE5cNwkDU7EzReDXPAhddu8/QMcTlbiaREPZNEIbsFTK68v+i+u0HFmkJaShTyHgmIy3GSuc7b7W/qjV+vyJhkwZMwA6yyiXDMYfU9aQMA7P4kpgOV96whhN/E3Fzyt9MmnyYh9CUkgar+wJA2p+fzJZ8OJW0MPh1pNLGnumeEGgfuyYa66WKCTGCLcnehwUTag85NBOf4DrPCpzRJBFtqIJrYkLXQIh9nfxmrefqrwCNGV85vl6SKr6Nx57IAkUUMWT3X27Sl8TUyJufq2D0m0Y4Rzwz7U58SklhVaSFAd9CN5FqJadpMTvSAoZ0Xco2F/uuAtouWC8tQ5/XSxeffdPiCiJfqHhnJNQd5nIadh616QZh1I1T2jq43NrsqMK5IQvs8HLyba2qhczkderPxgxTcZNz+SQ2phy20BR9pHiHT+t7bWyDKUN2DN7ejnxuEFP1IL2d2P9d7XRLRBlW7wFXHwfxLrng3vr+HRqqmxduyE7FSqQLs9cMEapYaBql/FXLissNjNcaD/sjQ6cq+HkRMo1D36AVLH0pvzndnzQkDrXkNYEpB9JGDI8KG9BvmecKjYJDJw1EHTKm9irx2LPL7Qgth+NjAM/9p9QGZ/U6MZc="
    - # ^^ GPG_PASSPHRASE
    - secure: "GCJ5fGq9Nj1zlxu+HCzYrgW/njcYsSdCzJDGBGd0dztZs2qQM/fTwxbNcnzFxbaoiWsdf/cAkSHPvyePP6H3HeWUCF30KdPz3FH+LbuzGxiDNMolpxk0pumlBuIX4AgzaEUwQOJHV6TJ5zMMETioYE7b/s7idAAKXSGmDipF3C4xk6GDyyPOHd/V+LMMjX6ZF3t0FgIfSmHxToUNDgL5xBRdUka+kooPZvNm9CdK4DGTDkiXu/GK0gj66Q3wuxUUjN+UQlKrOJCPLxSvlz3EFgX+nyt0u5DTwhXfN5WEFrVLvH7uLV8yqwilX/1Lq5ifutlf0z68EC8Ee3Wb5Yu5sm7VTZvzcrmyXGbn0RUcOQ5Kmk+c97nnoPjxdJDcC+INet7LUcx4RgA7GYuCvnqeIuAI5vpsrsDbKshAGg74VkxBUl1TOZa79nlPP9Y3VrrLcPYHECWfBWSxvw3/YxzQO/pnd0pKUmYyJSQJEDqj2OW/cz+TwpCbJqYBWpzF6Ko3aEYTKP84c95NVZD+jIhsxk6+qjrWpi97IUzJ2LHKOTupOVtHsU9EJPAEWbK9aUNUQGLlXgr0x+My8Q9cb5FnBX6AizxoAytUg3rmQ1NLK2cHhtMEUN0d9uOt0zdyJL6SVTPVmz/yeFViiFOJjeS7oJYWRO7ACe/mocCpBjKIFQw="
before_install:
  - openssl aes-256-cbc -K $encrypted_c91ff6812df7_key -iv $encrypted_c91ff6812df7_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --yes --batch --import codesigning.asc
jdk:
  - oraclejdk8
install: mvn clean install -P !ossrh -B -V -U
script:
- mvn deploy -P ossrh --settings mvnsettings.xml
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - 6.3/master
    - 6.3/develop                                                            
notifications:
  email:
    on_success: change
    on_failure: change